### ISSUE TITLE
Lambda testing error

### ISSUE THREAD

**Issue by LucMacPaquet** [aws-samples/amazon-pinpoint-connect-callback-requestor#5]
Hi

I'm new to Lambda (not to AWS btw) and got this error when testing the lambda fonction.

2020-04-16T14:10:00.897Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'toLowerCase' of undefined",
    "stack": [
        "TypeError: Cannot read property 'toLowerCase' of undefined",
        "    at Object.<anonymous> (/var/task/index.js:27:35)",
        "    at Module._compile (internal/modules/cjs/loader.js:1158:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)",
        "    at Module.load (internal/modules/cjs/loader.js:1002:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:901:14)",
        "    at Module.require (internal/modules/cjs/loader.js:1044:19)",
        "    at require (internal/modules/cjs/helpers.js:77:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"
    ]
}

Also, where should we paste these codes : package-lock.json and package.json ?

Thanks

**Comment by LucMacPaquet** [comment]
Error in the Lambda parameter
